#!/bin/bash

get_machine_layer_suffix()
{
  local MACHINE=$1

  case "${MACHINE}" in
  "raspberrypi3")
      echo "raspberrypi"
      ;;
  "imx6qdlsabresd")
      echo "freescale"
      ;;
  *)
      echo "todo-configure-machine-suffix"
      ;;
  esac
}

show_usage()
{
  cat << EOF

Usage: $(basename $0) <machine>

EOF
}

main()
{
  if [ $# -lt 1 ]; then
    show_usage
    exit 1
  fi
  local MACHINE="$1"

  if [ ! -d "$YOCTO_BUILD_DIR/conf" ]; then
    echo "ERROR: The 'conf' directory does not yet exist. Run the 'oe-init-build-env' script first."
    exit 1
  fi

  # Finish up Yocto build configuration
  MACHINE_LAYER_SUFFIX=$(get_machine_layer_suffix $MACHINE)
  sed -i "s@{{layers}}@$YOCTO_LAYERS_DIR@" "$YOCTO_BUILD_DIR/conf/bblayers.conf"
  sed -i "s@{{machine-layer-suffix}}@$MACHINE_LAYER_SUFFIX@" "$YOCTO_BUILD_DIR/conf/bblayers.conf"
  sed -i "s@{{machine}}@$MACHINE@" "$YOCTO_BUILD_DIR/conf/local.conf"
  sed -i "s@{{downloads}}@$YOCTO_DOWNLOADS_DIR@" "$YOCTO_BUILD_DIR/conf/local.conf"

  # Move newly generated Yocto build configuration files to Yocto cockpit directory and sym-link them back to Yocto build directory;
  # replace re-generated Yocto build configuration files with sym-links to their counterparts in Yocto cockpit directory otherwise
  if [ ! -f "$YOCTO_COCKPIT_DIR/conf/bblayers.conf" ]; then
    mkdir -p $YOCTO_COCKPIT_DIR/conf
    mv $YOCTO_BUILD_DIR/conf/bblayers.conf $YOCTO_COCKPIT_DIR/conf
  else
    rm $YOCTO_BUILD_DIR/conf/bblayers.conf
  fi
  ln -s $YOCTO_COCKPIT_DIR/conf/bblayers.conf $YOCTO_BUILD_DIR/conf/bblayers.conf

  if [ ! -f "$YOCTO_COCKPIT_DIR/conf/local.conf" ]; then
    mv $YOCTO_BUILD_DIR/conf/local.conf $YOCTO_COCKPIT_DIR/conf
  else
    rm $YOCTO_BUILD_DIR/conf/local.conf
  fi
  ln -s $YOCTO_COCKPIT_DIR/conf/local.conf $YOCTO_BUILD_DIR/conf/local.conf

  # Sym-link Yocto build script from Yocto cockpit directory into Yocto build directory 
  # (for easy use in `bind.bat bash` or `./bind.sh bash` sessions)
  if [ -f "$YOCTO_BUILD_SCRIPT" ] && [ ! -f "$YOCTO_BUILD_DIR/$(basename $YOCTO_BUILD_SCRIPT)" ]; then
    ln -s $YOCTO_BUILD_SCRIPT $YOCTO_BUILD_DIR/$(basename $YOCTO_BUILD_SCRIPT)
  fi
}

main $@
cd $YOCTO_BUILD_DIR