#!/bin/bash

show_usage()
{
  echo
  echo "Usage: $(basename $0) <machine>"
  echo
  exit 1
}

main()
{
  if [ $# -lt 1 ]; then
    show_usage
    exit 1
  fi
  local MACHINE="$1"

  export TEMPLATECONF=$YOCTO_SOURCES_DIR/meta-fotahub/conf
}

main $@